In [321]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Selecting input features (independent variable) and the target (dependent variable)

In [345]:
X = df.iloc[:, 1:-1].values
y = df.iloc[:, :1].values

In [346]:
print(X)

[[7420    4    2 ...    2    1    0]
 [8960    4    4 ...    3    0    0]
 [9960    3    2 ...    2    1    1]
 ...
 [3620    2    1 ...    0    0    0]
 [2910    3    1 ...    0    0    0]
 [3850    3    1 ...    0    0    0]]


In [347]:
print(y)

[[13300000]
 [12250000]
 [12250000]
 [12215000]
 [11410000]
 [10850000]
 [10150000]
 [10150000]
 [ 9870000]
 [ 9800000]
 [ 9800000]
 [ 9681000]
 [ 9310000]
 [ 9240000]
 [ 9240000]
 [ 9100000]
 [ 9100000]
 [ 8960000]
 [ 8890000]
 [ 8855000]
 [ 8750000]
 [ 8680000]
 [ 8645000]
 [ 8645000]
 [ 8575000]
 [ 8540000]
 [ 8463000]
 [ 8400000]
 [ 8400000]
 [ 8400000]
 [ 8400000]
 [ 8400000]
 [ 8295000]
 [ 8190000]
 [ 8120000]
 [ 8080940]
 [ 8043000]
 [ 7980000]
 [ 7962500]
 [ 7910000]
 [ 7875000]
 [ 7840000]
 [ 7700000]
 [ 7700000]
 [ 7560000]
 [ 7560000]
 [ 7525000]
 [ 7490000]
 [ 7455000]
 [ 7420000]
 [ 7420000]
 [ 7420000]
 [ 7350000]
 [ 7350000]
 [ 7350000]
 [ 7350000]
 [ 7343000]
 [ 7245000]
 [ 7210000]
 [ 7210000]
 [ 7140000]
 [ 7070000]
 [ 7070000]
 [ 7035000]
 [ 7000000]
 [ 6930000]
 [ 6930000]
 [ 6895000]
 [ 6860000]
 [ 6790000]
 [ 6790000]
 [ 6755000]
 [ 6720000]
 [ 6685000]
 [ 6650000]
 [ 6650000]
 [ 6650000]
 [ 6650000]
 [ 6650000]
 [ 6650000]
 [ 6629000]
 [ 6615000]
 [ 6615000]
 [ 6

### Splitting the dataset into training and test set

In [348]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=0)

### Training the Simple Linear Regression model on the Training set

In [349]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

### Predicting the Test set results

In [350]:
y_pred = regressor.predict(X_test)

### Evaluation metrics

In [ ]:

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"R² Score: {r2:.3f}")
print(f"Mean Absolute Error: {mae:,.0f}")
print(f"Root Mean Squared Error: {rmse:,.0f}")

R² Score: 0.666
Mean Absolute Error: 711,970
Root Mean Squared Error: 980,966


### Training the Random Forest Regression Model

In [ ]:
from sklearn.ensemble  import RandomForestRegressor
regressor = RandomForestRegressor (n_estimators=10,random_state=0)
regressor.fit(X, y)

c:\Users\letso\Documents\UDEMY\venv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(n_estimators=10, random_state=0)

### Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)

### Evaluation Metrics

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"R² Score: {r2:.3f}")
print(f"Mean Absolute Error: {mae:,.0f}")
print(f"Root Mean Squared Error: {rmse:,.0f}")

R² Score: 0.929
Mean Absolute Error: 303,280
Root Mean Squared Error: 452,786
